using Microsoft.Playwright;
var pw = await Playwright.CreateAsync();
var browser = await pw.Chromium.LaunchAsync(new() { Headless = true });
var ctx = await browser.NewContextAsync(new() { IgnoreHTTPSErrors = true });
var page = await ctx.NewPageAsync();
page.Console += (_, msg) => Console.WriteLine($"[CONSOLE {msg.Type}] {msg.Text}");
page.PageError += (_, err) => Console.WriteLine($"[PAGE ERROR] {err}");
Console.WriteLine("Navigating...");
var resp = await page.GotoAsync("https://localhost:7240/login", new() { Timeout = 30000, WaitUntil = WaitUntilState.NetworkIdle });
Console.WriteLine($"Status: {resp?.Status}");
Console.WriteLine("Waiting 10s for WASM...");
await Task.Delay(10000);
var content = await page.ContentAsync();
Console.WriteLine($"Content length: {content.Length}");
Console.WriteLine(content.Length > 2000 ? content[..2000] : content);
await browser.DisposeAsync();
pw.Dispose();
