// <auto-generated />
using System;
using FormValidationExperiments.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormValidationExperiments.Api.Migrations
{
    [DbContext(typeof(EctDbContext))]
    [Migration("20260211043734_AddDocumentContentColumns")]
    partial class AddDocumentContentColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormValidationExperiments.Shared.Models.INCAPDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CivilianIncomeLoss")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Documentation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("INCAPDetails");
                });

            modelBuilder.Entity("FormValidationExperiments.Shared.Models.LineOfDutyAppeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppealDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AppealOutcome")
                        .HasColumnType("int");

                    b.Property<string>("Appellant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppellateAuthorityId")
                        .HasColumnType("int");

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("NewEvidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalFinding")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppellateAuthorityId");

                    b.HasIndex("LineOfDutyCaseId");

                    b.ToTable("Appeals");
                });

            modelBuilder.Entity("FormValidationExperiments.Shared.Models.LineOfDutyAuthority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId");

                    b.ToTable("Authorities");
                });

            modelBuilder.Entity("FormValidationExperiments.Shared.Models.LineOfDutyCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuditComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClinicalDiagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CommanderReportReviewed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Component")
                        .HasColumnType("int");

                    b.Property<bool>("EightYearRuleApplies")
                        .HasColumnType("bit");

                    b.Property<int>("FinalFinding")
                        .HasColumnType("int");

                    b.Property<int>("INCAPId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncidentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IncidentDutyStatus")
                        .HasColumnType("int");

                    b.Property<int>("IncidentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("InitiationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InterimLODExpiration")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsAtDeployedLocation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAudited")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInterimLOD")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsMilitaryFacility")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPotentiallyUnfitting")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPriorServiceCondition")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsServiceAggravated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSexualAssaultCase")
                        .HasColumnType("bit");

                    b.Property<int>("MEDCONId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalFindings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalRecommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MedicalRecordsReviewed")
                        .HasColumnType("bit");

                    b.Property<bool>("MemberChoseMEDCON")
                        .HasColumnType("bit");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberRank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MemberStatementReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("MisconductExplanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherRelevantConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherSourcesDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OtherSourcesReviewed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OtherTestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtherTestResults")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OtherTestsDone")
                        .HasColumnType("bit");

                    b.Property<string>("PSCDocumentation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointOfContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PoliceReportsReviewed")
                        .HasColumnType("bit");

                    b.Property<int>("ProcessType")
                        .HasColumnType("int");

                    b.Property<string>("ProximateCause")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PsychiatricEvalCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PsychiatricEvalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PsychiatricEvalResults")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RequiresArcBoard")
                        .HasColumnType("bit");

                    b.Property<bool>("RestrictedReporting")
                        .HasColumnType("bit");

                    b.Property<string>("SARCCoordination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubstanceType")
                        .HasColumnType("int");

                    b.Property<int>("TotalTimelineDays")
                        .HasColumnType("int");

                    b.Property<string>("ToxicologyReport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TreatmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TreatmentFacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("WasMentallyResponsible")
                        .HasColumnType("bit");

                    b.Property<bool?>("WasUnderInfluence")
                        .HasColumnType("bit");

                    b.Property<string>("WitnessStatements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WitnessStatementsReviewed")
                        .HasColumnType("bit");

                    b.Property<int>("YearsOfService")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseId")
                        .IsUnique();

                    b.HasIndex("INCAPId")
                        .IsUnique();

                    b.HasIndex("MEDCONId")
                        .IsUnique();

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("FormValidationExperiments.Shared.Models.LineOfDutyDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("FormValidationExperiments.Shared.Models.MEDCONDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExtensionDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<bool>("OutOfLocalAreaLeaveApproved")
                        .HasColumnType("bit");

                    b.Property<string>("PhysicianMemo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TreatmentPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UsesInterimLOD")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("MEDCONDetails");
                });

            modelBuilder.Entity("FormValidationExperiments.Shared.Models.TimelineStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsibleAuthorityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StepDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimelineDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId");

                    b.HasIndex("ResponsibleAuthorityId");

                    b.ToTable("TimelineSteps");
                });

            modelBuilder.Entity("FormValidationExperiments.Shared.Models.LineOfDutyAppeal", b =>
                {
                    b.HasOne("FormValidationExperiments.Shared.Models.LineOfDutyAuthority", "AppellateAuthority")
                        .WithMany()
                        .HasForeignKey("AppellateAuthorityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FormValidationExperiments.Shared.Models.LineOfDutyCase", null)
                        .WithMany("Appeals")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppellateAuthority");
                });

            modelBuilder.Entity("FormValidationExperiments.Shared.Models.LineOfDutyAuthority", b =>
                {
                    b.HasOne("FormValidationExperiments.Shared.Models.LineOfDutyCase", null)
                        .WithMany("Authorities")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("FormValidationExperiments.Shared.Models.LineOfDutyCase", b =>
                {
                    b.HasOne("FormValidationExperiments.Shared.Models.INCAPDetails", "INCAP")
                        .WithOne()
                        .HasForeignKey("FormValidationExperiments.Shared.Models.LineOfDutyCase", "INCAPId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FormValidationExperiments.Shared.Models.MEDCONDetails", "MEDCON")
                        .WithOne()
                        .HasForeignKey("FormValidationExperiments.Shared.Models.LineOfDutyCase", "MEDCONId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("INCAP");

                    b.Navigation("MEDCON");
                });

            modelBuilder.Entity("FormValidationExperiments.Shared.Models.LineOfDutyDocument", b =>
                {
                    b.HasOne("FormValidationExperiments.Shared.Models.LineOfDutyCase", null)
                        .WithMany("Documents")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FormValidationExperiments.Shared.Models.TimelineStep", b =>
                {
                    b.HasOne("FormValidationExperiments.Shared.Models.LineOfDutyCase", null)
                        .WithMany("TimelineSteps")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FormValidationExperiments.Shared.Models.LineOfDutyAuthority", "ResponsibleAuthority")
                        .WithMany()
                        .HasForeignKey("ResponsibleAuthorityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ResponsibleAuthority");
                });

            modelBuilder.Entity("FormValidationExperiments.Shared.Models.LineOfDutyCase", b =>
                {
                    b.Navigation("Appeals");

                    b.Navigation("Authorities");

                    b.Navigation("Documents");

                    b.Navigation("TimelineSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
