// <auto-generated />
using System;
using ECTSystem.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECTSystem.Persistence.Migrations
{
    [DbContext(typeof(EctDbContext))]
    [Migration("20260412003053_ConstrainNvarcharMaxColumns")]
    partial class ConstrainNvarcharMaxColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECTSystem.Shared.Models.AuditComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId");

                    b.ToTable("AuditComments");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.Bookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId");

                    b.HasIndex("UserId", "LineOfDutyCaseId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Bookmarks", (string)null);
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.INCAPDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CivilianIncomeLoss")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documentation")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("INCAPDetails");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyAppeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppealDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AppealOutcome")
                        .HasColumnType("int");

                    b.Property<string>("Appellant")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("AppellateAuthorityId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewEvidence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalFinding")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AppellateAuthorityId");

                    b.HasIndex("LineOfDutyCaseId");

                    b.ToTable("Appeals");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyAuthority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Rank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId");

                    b.ToTable("Authorities");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbsentWithoutLeaveDate1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AbsentWithoutLeaveDate2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AbsentWithoutLeaveTime1")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AbsentWithoutLeaveTime2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AppointingAuthorityDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AppointingAuthorityNameRank")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AppointingAuthoritySignature")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ApprovingAuthorityDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApprovingAuthorityNameRank")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ApprovingAuthoritySignature")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("ApprovingFinding")
                        .HasColumnType("int");

                    b.Property<bool>("ApprovingReferForFormal")
                        .HasColumnType("bit");

                    b.Property<int?>("BoardFinding")
                        .HasColumnType("int");

                    b.Property<bool>("BoardReferForFormal")
                        .HasColumnType("bit");

                    b.Property<string>("CaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CheckedOutBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CheckedOutByName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("CheckedOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClinicalDiagnosis")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("CommanderDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CommanderFromLine")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CommanderNameRank")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("CommanderReportReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("CommanderSignature")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("CommanderToLine")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Component")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EightYearRuleApplies")
                        .HasColumnType("bit");

                    b.Property<int>("FinalFinding")
                        .HasColumnType("int");

                    b.Property<string>("FromLine")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("INCAPId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncidentDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("IncidentDutyStatus")
                        .HasColumnType("int");

                    b.Property<int>("IncidentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("InitiationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InterimLODExpiration")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAFROTC")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAtDeployedLocation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAudited")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCheckedOut")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeployedLocation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGMU")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInterimLOD")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMTF")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsMilitaryFacility")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPotentiallyUnfitting")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPriorServiceCondition")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRMU")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsServiceAggravated")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSexualAssaultCase")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUSAFA")
                        .HasColumnType("bit");

                    b.Property<string>("LegalReviewDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LegalReviewText")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("LegalReviewerNameRank")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LegalReviewerSignature")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LodBoardChairDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LodBoardChairNameRank")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LodBoardChairSignature")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("MEDCONId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalFindings")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MedicalRecommendation")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("MedicalRecordsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("MedicalReviewDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedicalReviewText")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MedicalReviewerNameRank")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MedicalReviewerSignature")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("MemberChoseMEDCON")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MemberDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("MemberName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("MemberOrdersEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberOrdersEndTime")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MemberOrdersStartTime")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MemberRank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("MemberStatementReviewed")
                        .HasColumnType("bit");

                    b.Property<bool>("MilitaryPoliceReportsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("MisconductExplanation")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("NotifiedMedicalUnitTimely")
                        .HasColumnType("bit");

                    b.Property<bool>("OsiReportsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("OtherRelevantConditions")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("OtherSourcesDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("OtherSourcesReviewed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OtherTestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtherTestResults")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool?>("OtherTestsDone")
                        .HasColumnType("bit");

                    b.Property<string>("PSCDocumentation")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PointOfContact")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PoliceReportsReviewed")
                        .HasColumnType("bit");

                    b.Property<int>("ProcessType")
                        .HasColumnType("int");

                    b.Property<string>("ProviderDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderNameRank")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProviderSignature")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ProximateCause")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool?>("PsychiatricEvalCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PsychiatricEvalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PsychiatricEvalResults")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool?>("RequiresArcBoard")
                        .HasColumnType("bit");

                    b.Property<bool?>("RestrictedReporting")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SARCCoordination")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ServiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("SjaConcurs")
                        .HasColumnType("bit");

                    b.Property<string>("SjaDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SjaNameRank")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("SubmittedMedicalDocumentsTimely")
                        .HasColumnType("bit");

                    b.Property<int?>("SubstanceType")
                        .HasColumnType("int");

                    b.Property<int>("TotalTimelineDays")
                        .HasColumnType("int");

                    b.Property<string>("ToxicologyReport")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("TreatmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TreatmentFacilityName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Unit")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("WasAbsentWithLeave")
                        .HasColumnType("bit");

                    b.Property<bool>("WasAbsentWithoutLeave")
                        .HasColumnType("bit");

                    b.Property<bool?>("WasMentallyResponsible")
                        .HasColumnType("bit");

                    b.Property<bool>("WasOnDuty")
                        .HasColumnType("bit");

                    b.Property<bool>("WasOnIDT")
                        .HasColumnType("bit");

                    b.Property<bool>("WasPresentForDuty")
                        .HasColumnType("bit");

                    b.Property<bool?>("WasUnderInfluence")
                        .HasColumnType("bit");

                    b.Property<string>("WingCcSignature")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("WitnessNameAddress1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WitnessNameAddress2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WitnessNameAddress3")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WitnessNameAddress4")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WitnessNameAddress5")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("WitnessStatementsReviewed")
                        .HasColumnType("bit");

                    b.Property<int>("YearsOfService")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseId")
                        .IsUnique()
                        .HasFilter("[CaseId] IS NOT NULL");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("INCAPId")
                        .IsUnique()
                        .HasFilter("[INCAPId] IS NOT NULL");

                    b.HasIndex("MEDCONId")
                        .IsUnique()
                        .HasFilter("[MEDCONId] IS NOT NULL");

                    b.HasIndex("MemberId");

                    b.HasIndex("MemberId", "CreatedDate")
                        .HasDatabaseName("IX_Cases_MemberId_CreatedDate");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.MEDCONDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExtensionDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OutOfLocalAreaLeaveApproved")
                        .HasColumnType("bit");

                    b.Property<string>("PhysicianMemo")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TreatmentPlan")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("UsesInterimLOD")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("MEDCONDetails");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Component")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleInitial")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ServiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Recipient")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.WitnessStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId");

                    b.ToTable("WitnessStatements");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.WorkflowModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WorkflowModules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Air Force Reserve Command workflow module.",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "AFRC",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Air National Guard workflow module.",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ANG",
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.WorkflowStateHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnteredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("WorkflowState")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId", "WorkflowState");

                    b.HasIndex("LineOfDutyCaseId", "CreatedDate", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("WorkflowStateHistory", (string)null);
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.WorkflowStateLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("WorkflowTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowTypeId");

                    b.HasIndex("Name", "WorkflowTypeId")
                        .IsUnique();

                    b.ToTable("WorkflowStates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enter member identification and incident details to initiate the LOD case.",
                            DisplayOrder = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Member Information Entry",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Medical technician reviews the injury/illness and documents clinical findings.",
                            DisplayOrder = 2,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Medical Technician Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Medical officer reviews the technician's findings and provides a clinical assessment.",
                            DisplayOrder = 3,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Medical Officer Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Unit commander reviews the case and submits a recommendation for the LOD determination.",
                            DisplayOrder = 4,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Unit CC Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wing Judge Advocate reviews the case for legal sufficiency and compliance.",
                            DisplayOrder = 5,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wing JA Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Appointing authority reviews the case and issues a formal LOD determination.",
                            DisplayOrder = 6,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Appointing Authority Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wing commander reviews the case and renders a preliminary LOD determination.",
                            DisplayOrder = 7,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wing CC Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Board medical technician reviews the case file for completeness and accuracy.",
                            DisplayOrder = 8,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Board Technician Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Board medical officer reviews all medical evidence and provides a formal assessment.",
                            DisplayOrder = 9,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Board Medical Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Board legal counsel reviews the case for legal sufficiency before final decision.",
                            DisplayOrder = 10,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Board Legal Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Board administrative officer finalizes the case package and prepares the formal determination.",
                            DisplayOrder = 11,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Board Admin Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "LOD determination has been finalized and the case is closed.",
                            DisplayOrder = 12,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Completed",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enter member identification and incident details to initiate the LOD case.",
                            DisplayOrder = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Member Information Entry",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Medical technician reviews the injury/illness and documents clinical findings.",
                            DisplayOrder = 2,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Medical Technician Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Medical officer reviews the technician's findings and provides a clinical assessment.",
                            DisplayOrder = 3,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Medical Officer Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Unit commander reviews the case and submits a recommendation for the LOD determination.",
                            DisplayOrder = 4,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Unit CC Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wing Judge Advocate reviews the case for legal sufficiency and compliance.",
                            DisplayOrder = 5,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wing JA Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Appointing authority reviews the case and issues a formal LOD determination.",
                            DisplayOrder = 6,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Appointing Authority Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wing commander reviews the case and renders a preliminary LOD determination.",
                            DisplayOrder = 7,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wing CC Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Board medical technician reviews the case file for completeness and accuracy.",
                            DisplayOrder = 8,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Board Technician Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Board medical officer reviews all medical evidence and provides a formal assessment.",
                            DisplayOrder = 9,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Board Medical Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Board legal counsel reviews the case for legal sufficiency before final decision.",
                            DisplayOrder = 10,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Board Legal Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Board administrative officer finalizes the case package and prepares the formal determination.",
                            DisplayOrder = 11,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Board Admin Review",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "LOD determination has been finalized and the case is closed.",
                            DisplayOrder = 12,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Completed",
                            RowVersion = new byte[0],
                            WorkflowTypeId = 2
                        });
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.WorkflowType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("WorkflowModuleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowModuleId");

                    b.HasIndex("Name", "WorkflowModuleId")
                        .IsUnique();

                    b.ToTable("WorkflowTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Informal LOD determination process.",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Informal",
                            RowVersion = new byte[0],
                            WorkflowModuleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Formal LOD determination process.",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Formal",
                            RowVersion = new byte[0],
                            WorkflowModuleId = 1
                        });
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.AuditComment", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyCase", null)
                        .WithMany("AuditComments")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.Bookmark", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyCase", null)
                        .WithMany()
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyAppeal", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyAuthority", "AppellateAuthority")
                        .WithMany()
                        .HasForeignKey("AppellateAuthorityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyCase", null)
                        .WithMany("Appeals")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("AppellateAuthority");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyAuthority", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyCase", null)
                        .WithMany("Authorities")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyCase", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.INCAPDetails", "INCAP")
                        .WithOne()
                        .HasForeignKey("ECTSystem.Shared.Models.LineOfDutyCase", "INCAPId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ECTSystem.Shared.Models.MEDCONDetail", "MEDCON")
                        .WithOne()
                        .HasForeignKey("ECTSystem.Shared.Models.LineOfDutyCase", "MEDCONId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ECTSystem.Shared.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("INCAP");

                    b.Navigation("MEDCON");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyDocument", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyCase", null)
                        .WithMany("Documents")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.Notification", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyCase", null)
                        .WithMany("Notifications")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.WitnessStatement", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyCase", null)
                        .WithMany("WitnessStatements")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.WorkflowStateHistory", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyCase", null)
                        .WithMany("WorkflowStateHistories")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.WorkflowStateLookup", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.WorkflowType", "WorkflowType")
                        .WithMany("WorkflowStates")
                        .HasForeignKey("WorkflowTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkflowType");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.WorkflowType", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.WorkflowModule", "WorkflowModule")
                        .WithMany("WorkflowTypes")
                        .HasForeignKey("WorkflowModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkflowModule");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyCase", b =>
                {
                    b.Navigation("Appeals");

                    b.Navigation("AuditComments");

                    b.Navigation("Authorities");

                    b.Navigation("Documents");

                    b.Navigation("Notifications");

                    b.Navigation("WitnessStatements");

                    b.Navigation("WorkflowStateHistories");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.WorkflowModule", b =>
                {
                    b.Navigation("WorkflowTypes");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.WorkflowType", b =>
                {
                    b.Navigation("WorkflowStates");
                });
#pragma warning restore 612, 618
        }
    }
}
