// <auto-generated />
using System;
using ECTSystem.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECTSystem.Persistence.Migrations
{
    [DbContext(typeof(EctDbContext))]
    [Migration("20260224170307_AddWorkflowStepHistory")]
    partial class AddWorkflowStepHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECTSystem.Shared.Models.CaseBookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookmarkedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId");

                    b.HasIndex("UserId", "LineOfDutyCaseId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("CaseBookmarks");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.INCAPDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CivilianIncomeLoss")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documentation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("INCAPDetails");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyAppeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppealDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AppealOutcome")
                        .HasColumnType("int");

                    b.Property<string>("Appellant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppellateAuthorityId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewEvidence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalFinding")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppellateAuthorityId");

                    b.HasIndex("LineOfDutyCaseId");

                    b.ToTable("Appeals");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyAuthority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId");

                    b.ToTable("Authorities");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbsentWithoutLeaveDate1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbsentWithoutLeaveDate2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbsentWithoutLeaveTime1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbsentWithoutLeaveTime2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointingAuthorityDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointingAuthorityNameRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointingAuthoritySignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovingAuthorityDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovingAuthorityNameRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovingAuthoritySignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ApprovingFinding")
                        .HasColumnType("int");

                    b.Property<bool>("ApprovingReferForFormal")
                        .HasColumnType("bit");

                    b.Property<string>("AuditComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BoardFinding")
                        .HasColumnType("int");

                    b.Property<bool>("BoardReferForFormal")
                        .HasColumnType("bit");

                    b.Property<string>("CaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClinicalDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommanderDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommanderFromLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommanderNameRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CommanderReportReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("CommanderSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommanderToLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Component")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EightYearRuleApplies")
                        .HasColumnType("bit");

                    b.Property<int>("FinalFinding")
                        .HasColumnType("int");

                    b.Property<string>("FromLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("INCAPId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncidentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IncidentDutyStatus")
                        .HasColumnType("int");

                    b.Property<int>("IncidentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("InitiationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InterimLODExpiration")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAFROTC")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAtDeployedLocation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAudited")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeployedLocation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGMU")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInterimLOD")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMTF")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsMilitaryFacility")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPotentiallyUnfitting")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPriorServiceCondition")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRMU")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsServiceAggravated")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSexualAssaultCase")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUSAFA")
                        .HasColumnType("bit");

                    b.Property<string>("LegalReviewDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalReviewText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalReviewerNameRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalReviewerSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LodBoardChairDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LodBoardChairNameRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LodBoardChairSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MEDCONId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalRecommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MedicalRecordsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("MedicalReviewDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalReviewText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalReviewerNameRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalReviewerSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MemberChoseMEDCON")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MemberDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("MemberName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MemberOrdersEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberOrdersEndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberOrdersStartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MemberStatementReviewed")
                        .HasColumnType("bit");

                    b.Property<bool>("MilitaryPoliceReportsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("MisconductExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("NotifiedMedicalUnitTimely")
                        .HasColumnType("bit");

                    b.Property<bool>("OsiReportsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("OtherRelevantConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherSourcesDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OtherSourcesReviewed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OtherTestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtherTestResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OtherTestsDone")
                        .HasColumnType("bit");

                    b.Property<string>("PSCDocumentation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointOfContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PoliceReportsReviewed")
                        .HasColumnType("bit");

                    b.Property<int>("ProcessType")
                        .HasColumnType("int");

                    b.Property<string>("ProviderDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderNameRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProximateCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PsychiatricEvalCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PsychiatricEvalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PsychiatricEvalResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RequiresArcBoard")
                        .HasColumnType("bit");

                    b.Property<bool?>("RestrictedReporting")
                        .HasColumnType("bit");

                    b.Property<string>("SARCCoordination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SjaConcurs")
                        .HasColumnType("bit");

                    b.Property<string>("SjaDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SjaNameRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SubmittedMedicalDocumentsTimely")
                        .HasColumnType("bit");

                    b.Property<int?>("SubstanceType")
                        .HasColumnType("int");

                    b.Property<int>("TotalTimelineDays")
                        .HasColumnType("int");

                    b.Property<string>("ToxicologyReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TreatmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TreatmentFacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WasAbsentWithLeave")
                        .HasColumnType("bit");

                    b.Property<bool>("WasAbsentWithoutLeave")
                        .HasColumnType("bit");

                    b.Property<bool?>("WasMentallyResponsible")
                        .HasColumnType("bit");

                    b.Property<bool>("WasOnDuty")
                        .HasColumnType("bit");

                    b.Property<bool>("WasOnIDT")
                        .HasColumnType("bit");

                    b.Property<bool>("WasPresentForDuty")
                        .HasColumnType("bit");

                    b.Property<bool?>("WasUnderInfluence")
                        .HasColumnType("bit");

                    b.Property<string>("WingCcSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WitnessNameAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WitnessNameAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WitnessNameAddress3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WitnessNameAddress4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WitnessNameAddress5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WitnessStatements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WitnessStatementsReviewed")
                        .HasColumnType("bit");

                    b.Property<int>("WorkflowState")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfService")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseId")
                        .IsUnique()
                        .HasFilter("[CaseId] IS NOT NULL");

                    b.HasIndex("INCAPId")
                        .IsUnique();

                    b.HasIndex("MEDCONId")
                        .IsUnique();

                    b.HasIndex("MemberId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyWorkflowStateLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LineOfDutyWorkflowState", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Enter member identification and incident details to initiate the LOD case.",
                            DisplayOrder = 1,
                            Name = "Member Information Entry"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Medical technician reviews the injury/illness and documents clinical findings.",
                            DisplayOrder = 2,
                            Name = "Medical Technician Review"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Medical officer reviews the technician's findings and provides a clinical assessment.",
                            DisplayOrder = 3,
                            Name = "Medical Officer Review"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Unit commander reviews the case and submits a recommendation for the LOD determination.",
                            DisplayOrder = 4,
                            Name = "Unit CC Review"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Wing Judge Advocate reviews the case for legal sufficiency and compliance.",
                            DisplayOrder = 5,
                            Name = "Wing JA Review"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Appointing authority reviews the case and issues a formal LOD determination.",
                            DisplayOrder = 6,
                            Name = "Appointing Authority Review"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Wing commander reviews the case and renders a preliminary LOD determination.",
                            DisplayOrder = 7,
                            Name = "Wing CC Review"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Board medical technician reviews the case file for completeness and accuracy.",
                            DisplayOrder = 8,
                            Name = "Board Technician Review"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Board medical officer reviews all medical evidence and provides a formal assessment.",
                            DisplayOrder = 9,
                            Name = "Board Medical Review"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Board legal counsel reviews the case for legal sufficiency before final decision.",
                            DisplayOrder = 10,
                            Name = "Board Legal Review"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Board administrative officer finalizes the case package and prepares the formal determination.",
                            DisplayOrder = 11,
                            Name = "Board Admin Review"
                        },
                        new
                        {
                            Id = 12,
                            Description = "LOD determination has been finalized and the case is closed.",
                            DisplayOrder = 12,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.MEDCONDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExtensionDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OutOfLocalAreaLeaveApproved")
                        .HasColumnType("bit");

                    b.Property<string>("PhysicianMemo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TreatmentPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UsesInterimLOD")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("MEDCONDetails");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Component")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Recipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.TimelineStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResponsibleAuthorityId")
                        .HasColumnType("int");

                    b.Property<string>("SignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StepDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimelineDays")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowState")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId");

                    b.HasIndex("ResponsibleAuthorityId");

                    b.ToTable("TimelineSteps");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.WorkflowStepHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineOfDutyCaseId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowState")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LineOfDutyCaseId", "WorkflowState");

                    b.ToTable("WorkflowStepHistories");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.CaseBookmark", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyCase", null)
                        .WithMany()
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyAppeal", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyAuthority", "AppellateAuthority")
                        .WithMany()
                        .HasForeignKey("AppellateAuthorityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyCase", null)
                        .WithMany("Appeals")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppellateAuthority");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyAuthority", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyCase", null)
                        .WithMany("Authorities")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyCase", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.INCAPDetails", "INCAP")
                        .WithOne()
                        .HasForeignKey("ECTSystem.Shared.Models.LineOfDutyCase", "INCAPId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ECTSystem.Shared.Models.MEDCONDetail", "MEDCON")
                        .WithOne()
                        .HasForeignKey("ECTSystem.Shared.Models.LineOfDutyCase", "MEDCONId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ECTSystem.Shared.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("INCAP");

                    b.Navigation("MEDCON");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyDocument", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyCase", null)
                        .WithMany("Documents")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.Notification", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyCase", null)
                        .WithMany("Notifications")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.TimelineStep", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyCase", null)
                        .WithMany("TimelineSteps")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyAuthority", "ResponsibleAuthority")
                        .WithMany()
                        .HasForeignKey("ResponsibleAuthorityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ResponsibleAuthority");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.WorkflowStepHistory", b =>
                {
                    b.HasOne("ECTSystem.Shared.Models.LineOfDutyCase", "LineOfDutyCase")
                        .WithMany("WorkflowStepHistories")
                        .HasForeignKey("LineOfDutyCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LineOfDutyCase");
                });

            modelBuilder.Entity("ECTSystem.Shared.Models.LineOfDutyCase", b =>
                {
                    b.Navigation("Appeals");

                    b.Navigation("Authorities");

                    b.Navigation("Documents");

                    b.Navigation("Notifications");

                    b.Navigation("TimelineSteps");

                    b.Navigation("WorkflowStepHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
